### PR TITLE
 barrels*** and some Miscellaneous things.

### PR DESCRIPTION
**Pull request by Viswas-Programs**
Added barrels***
Fixed the barrels being too large, and invisibly being a rectangle.
MISC:
1 -> Added grenade entity
***The players STILL don't take damage from exploding the barrel, and after 4 hits it doesn't produce smoke
All of these issues will be fixed in the near future ( I hope so! :D)

### CODE REVIEW

**Comment by North-West-Wind** [comment]
The reason the player didn't take any damage is because the player does not collide with the explosion hitbox (which doesn't exist as you only used the barrel's original hitbox)

**Comment by Viswas-Programs** [comment]
so what can I do for that bro?

**Comment by North-West-Wind** [comment]
Change the barrel's hitbox when the barrel dies. Check out the `GameObject` class as `Barrel` extends it.
https://github.com/North-West-Wind/opensurviv-server/blob/main/src/types/objects.ts

You should see the `hitbox` property of `GameObject`. To change it in `Barrel`, just call `this.hitbox = <new hitbox>`.
I will let you figure out where this statement should be put.

**Comment by Viswas-Programs** [comment]
in the constructor?

bro, tbh, I am learning classes in JS right now bro
I only familiar in Python and C++.

**Comment by North-West-Wind** [comment]
The `tick`/`die` method of course. The constructor is only used to initialize the object and will not be useful after the game starts running. You should have known about classes from C++?

**Comment by Viswas-Programs** [comment]
Ohh yeah, and in python it's a bit different to.
The constructor does all the things when called the class.
Confused between the two

**Comment by Viswas-Programs** [comment]
Thank you for the help again bro
After my school, i will implement it

**Pull request closed without merging**
